FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# MyMessageTest

To show a simple API test 

## MessageSerice [/message]

### Get Message of today [GET]

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "message": "Hello from Zurich!"
            }
        ]